#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
# This file is a part of the vllm-ascend project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: 'e2e test'

on:
  push:
    branches:
      - "main"
    paths:
      - '*.txt'
      - '**/*.py'
      - '.github/workflows/vllm_ascend_test.yaml'
  pull_request:
    branches:
      - "main"
    paths:
      - '*.txt'
      - '**/*.py'
      - '.github/workflows/vllm_ascend_test.yaml'

  issue_comment:
    types: [created]

# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    name: vLLM Ascend test (self-host)
    runs-on: ubuntu-latest  # actionlint-ignore: runner-label
    steps:
      - name: Checkout vllm-project/vllm-ascend repo
        uses: actions/checkout@v4

      - name: Check current directory
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -la

      - name: Checkout vllm-project/vllm repo
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm
          path: vllm

      - name: move vllm
        working-directory: vllm
        run: |
          mv vllm /home/runner/work/vllm
        working-directory: /home/runner/work/

      - name: Install vllm-project/vllm from source
        working-directory: vllm
        run: |
          VLLM_TARGET_DEVICE=empty pip install -e .

      - name: Install vllm-project/vllm-ascend
        run: |
          pip install -e .

